agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, 
    AgentUpdateView, AgentDeleteView
)

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadDeleteView,
    LeadJsonView, FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('kanban/', include('kanban.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM Engenharia de Software</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% include 'messages.html' %}
        {% block content %}
        {% endblock content %}
    </div>
    {% include "scripts.html" %}
</body>
</html>

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/logo.jpg' %}">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM Engenharia de Software
        </h1>
      </div>
    </div>
</section>
{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="p-4 border-l-4
        {% if message.tags == 'success' %}
        bg-green-50 border-green-400
        {% elif message.tags == 'info' %}
        bg-blue-50 border-blue-400
        {% elif message.tags == 'warning' %}
        bg-yellow-50 border-yellow-400
        {% else %}
        bg-red-50 border-red-400
        {% endif %}
        ">
            <p class="text-sm
            {% if message.tags == 'success' %}
            text-green-700
            {% elif message.tags == 'info' %}
            text-blue-700
            {% elif message.tags == 'warning' %}
            text-yellow-700
            {% else %}
            text-red-700
            {% endif %}
            ">
                {{ message }}
            </p>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<header class="text-gray-700 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a href="{% url 'login' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <img src="{% static 'images/bulb.png' %}" width="50" height="50">
        <span class="ml-3 text-xl">CRM Engenharia de Software</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% if not request.user.is_authenticated %}
          <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Registrar</a>
        {% else %}
          {% if request.user.is_organisor %}
          <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Vendedores</a>
          {% endif %}
          <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
        {% endif %}
      </nav>
      {% if request.user.is_authenticated %}
        Logado como: {{ request.user.username }}
        <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
          Sair
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
      {% else %}
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
          Entrar
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
      </a>
      {% endif %}
    </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>

templates/visualizacao.html
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="./../css/visualizacao.css">


</head>

<body>

    <form class="row g-3">
        <div class="col-md-6">
            <label for="nomeCliente" class="form-label">Nome do cliente</label>
            <input type="text" class="form-control" id="nomeCliente" placeholder="Ana Cristina Stancioli Silva">
        </div>
        <div class="col-md-6">
            <label for="nomeVendedor" class="form-label">Vendedor responsável</label>
            <input type="text" class="form-control" id="nomeVendedor" placeholder="Bernardo">
        </div>
        <div class="col-12">
            <label for="descricao" class="form-label">Descrição</label>
            <textarea class="form-control" id="descricao" rows="3" placeholder="A cliente deseja um sistema para gerenciar os pacientes em seu consultório, além dos procedimentos realizados."></textarea>
        </div>
        <div class="col-12">
            <label for="areaAtuacao" class="form-label">Área de atuação</label>
            <input type="text" class="form-control" id="areaAtuacao" placeholder="Consultório médico (dermatológico).">
        </div>
        <div class="col-md-6">
            <label for="nomeEmpresa" class="form-label">Nome da empresa</label>
            <input type="text" class="form-control" id="nomeEmpresa" placeholder="Consultório Médico ACS">
        </div>
        <div class="col-md-4">
            <label for="statusCliente" class="form-label">Status do cliente</label>
            <input type="text" class="form-control" id="statusCliente" placeholder="Primeiro contato">
        </div>
        <div class="col-md-2">
            <label for="inputZip" class="form-label">Telefone</label>
            <input type="text" class="form-control" id="inputZip" placeholder="(31)3291-4521">
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
            <button type="submit" class="btn btn-lg btn-outline-secondary">Editar informações</button>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
            <button type="submit" class="btn btn-lg btn-outline-danger">Excluir cliente</button>
        </div>
    </form>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    
</body>

</html>